# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'

    session:
        enabled: true            # antes era "true" como booleano
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        cookie_path: '/'
        cookie_domain: null
        name: SESSID_SYMFONY

    # esi: true
    # fragments: true
