# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'

    session:
        enabled: true            # antes era "true" como booleano
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        cookie_path: '/'
        cookie_domain: null
        name: SESSID_SYMFONY

    # esi: true
    # fragments: true

    # Ajuste para evitar problemas de caché en las páginas
    http_method_override: false
    http_cache:
        # Desactivar la caché HTTP para evitar problemas de recarga
        enabled: '%kernel.debug%'
        default_ttl: 0
    
    assets:
        # Configuración simple con valor fijo para versión
        version: '1.0.0'
