vich_uploader:
    db_driver: orm
    mappings:
        denuncia:
            uri_prefix: /uploads/denuncias
            upload_destination: '%kernel.project_dir%/public/uploads/denuncias'
            namer: Vich\UploaderBundle\Naming\UniqidNamer