controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
favicon:
    path: /favicon.ico
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirect
    defaults:
        path: '/images/default-favicon.png'
        permanent: true
